# .rubocop.yml
require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec


AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

# Rails-specific configuration
Rails:
  Enabled: true

# Add or adjust rules as needed
